[build-system]
requires = ["flit_core >=3.2,<4", "click"]
build-backend = "flit_core.buildapi"

[project]
name = "alany"
authors = [{name = "Vlad100"}]
readme = "README.md"
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/anony-oss/alany"
